//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_Vehicular
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int ID { get; set; }
        public string BRAND { get; set; }
        public string MODEL { get; set; }
        public string YEAR { get; set; }
        public string DOORS { get; set; }
        public string TRANSMISSION { get; set; }
        public string FUEL { get; set; }
        public string COLOR { get; set; }
        public string INTERIOR_COLOR { get; set; }
        public int STATUS { get; set; }
        public int ASSIGNER_DRIVER { get; set; }
    }
}
