//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_Vehicular
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public int ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string DATE_OF_BIRTH { get; set; }
        public string IDENTIFICATION { get; set; }
        public Nullable<int> DRIVERS_LICENSE { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string IMG { get; set; }
        public int ID_REGISTER_USER { get; set; }
    }
}
